### ISSUE TITLE
Documentation and KT

### ISSUE THREAD

**Issue by arka1997** [OscuroBok/OscuroBok_dashboard_FE#5]
Please go through the codebase of Frontend, and create a simple diagram and brief descriptions

**Comment by arka1997** [comment]
This is issue for creating documentation, after going through codebase and getting KT: https://github.com/orgs/OscuroBok/projects/3/views/1

**Comment by RutikKulkarni** [comment]
https://github.com/OscuroBok/OscuroBok_dashboard_FE/issues/6

**Comment by arka1997** [comment]
https://github.com/OscuroBok/OscuroBok_dashboard_FE/issues/4

**Comment by arka1997** [comment]
Not needed any more
